//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int video_id { get; set; }
        public string video_name { get; set; }
        public string video_customname { get; set; }
        public string video_type { get; set; }
        public string video_data { get; set; }
        public int subject_id { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
